### ISSUE TITLE
Starter build missing from main

### ISSUE THREAD

**Issue by phil-fradkin** [deepgenomics/GenomeKit#115]
Hello dear genomekit team. Thanks for releasing the project it's been tremendously useful - I've been using it to help folks start using a model we made https://github.com/bowang-lab/Orthrus?tab=readme-ov-file#create-and-set-up-the-environment

It looks like the starter build link which is specified in [the docs ](https://deepgenomics.github.io/GenomeKit/quickstart.html#initial-data-access) now points to an empty page:

https://raw.githubusercontent.com/deepgenomics/GenomeKit/main/starter/build.sh

However, https://raw.githubusercontent.com/deepgenomics/GenomeKit/v6.0.3/starter/build.sh is still available. 

Is it possible to bring that page back online?

Thanks

**Comment by ovesh** [comment]
It was removed in #14 (which didn't create a release, and that's why the docs haven't been published).
The scripts are replaced with a docker image and the relevant docs have been updated on the docs site. I can force a release to publish the docs. 
Can you have a look at the new docs https://github.com/deepgenomics/GenomeKit/blob/main/docs-src/quickstart.rst#generating-data-with-docker ? Let me know what you think.

**Comment by s22chan** [comment]
Hey Phil, Avishai was able to get AWS to serve the OSS data, so you can use https://github.com/deepgenomics/GenomeKit/releases/tag/v6.2.0 and just have it download like back at DG.

**Comment by phil-fradkin** [comment]
Sorry I haven't gotten around to replying earlier - this is awesome, thanks a lot. It will simplify instructions to new users a lot
